resolver: lts-14.27

packages:
- '.'

extra-deps:
- some-1.0.1
- stylish-haskell-0.11.0.0
- hlint-2.1.26
- haskeline-0.8.0.0
- lsp-1.0.0.1
- lsp-types-1.0.0.1

flags:
  haskeline:
    terminfo: false
